run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - unconvert
    - gosec
    - noctx
    - gocritic
    - goconst
    - nilerr
    - contextcheck
    - whitespace

linters-settings:
  errcheck:
    check-blank: true     # Проверка игнорирования ошибок через _