services:
  postgres:
    image: postgres:14.10-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 1s
    env_file:
      - .env

  api-gateway:
    build: ./
    ports:
      - "8081:${APP_ADDRESS}"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
