services:
  postgres:
    image: postgres:14.10-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 1s
    env_file:
      - .env

  api-gateway:
    build: ./
    ports:
      - "8081:${API_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
volumes:
  pgdata: