name: Go Lint

on:
  push:
    branches: [main] # Запускать при пуше в main
  pull_request:
    branches: [main] # Запускать при создании PR в main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' # Укажите версию Go, которую вы используете

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      - name: Run golangci-lint
        run: |
          golangci-lint run --timeout=5m